#!/bin/bash

# Most of the below utilites depends on the "jq" tool for parsing the 
# See https://stedolan.github.io/jq/ for installing jq tool.
# JSON reponse from JIRA rest API. Below environment variables need to
# be configured for the tool to function.
# JIRA_USERNAME - Email id of the JIRA account
# JIRA_TOKEN - JIRA api token for the user account
# JIRA_URL - JIRA enterprise cloud URL

# Helper method to get the JIRA issue title for given issue id. 
jira_get_issue_title() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_get_issue_title <issue-id>"
		return
	fi

	_jira_get_issue_json $1 | jq -r '.fields.summary'
}


jira_get_parent_issue_key() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_get_parent_issue_key <issue-id>"
		return
	fi

	_jira_get_issue_json $1 | jq -r '.fields.parent.key'
}


jira_get_issue_assignee() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_get_issue_assignee <issue-id>"
		return
	fi

	_jira_get_issue_json $1 | jq -r '.fields.assignee.accountId'	
}

jira_get_siblings() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_get_siblings <issue-id>"
		return
	fi

	local parent_issue
	parent_issue=`jira_get_parent_issue_key $1`

	if ! [[ -z $parent_issue || $parent_issue == null ]]; then
		_jira_get_issue_json $parent_issue | jq  -r '.fields.subtasks[] | .key + " " + .fields.summary' 
	fi
}

jira_filter_issue_key() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_filter_issue_key <issue-id>"
		return
	fi
	
	echo "$1" | sed 's/[^a-zA-Z0-9]/-/g' | tr -s '-' | cut -d- -f1-2
}

jira_get_issue_type() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_get_issue_type <issue-id>"
		return
	fi

	_jira_get_issue_json $1 | jq -r '.fields.issuetype.name'	
}

jira_get_outward_linked_issue() {
	if [[ $# -ne 1 ]]; then
		echo "Usage: jira_get_outward_linked_issue <issue-id>"
		return
	fi

	_jira_get_issue_json $1 | jq -r '.fields.issuelinks[0].outwardIssue.key'
}

_jira_get_issue_json() {
	local issue_key
	issue_key=`jira_filter_issue_key "$1"`
	curl -s --user "$JIRA_USERNAME:$JIRA_TOKEN" "$JIRA_URL/rest/api/3/issue/$issue_key"
}


