#!/bin/bash

# Not sure how this is useful to others.
# This are my venv setups for Python, Ruby and Node

nvm_init() {
	unalias nvm
	export NVM_DIR="$HOME/.nvm"
	. "/usr/local/opt/nvm/nvm.sh"
}

nvm_init1() {
	#remove nvm alias to avoid recursion
	unalias nvm
	
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

rvm_init() {
	#remove rvm alias to avoid recursion
	unalias rvm

	# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
	export PATH="$PATH:$HOME/.rvm/bin"

	[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
}


pyenv_init() {
	#remove alias
	unalias pyenv

	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
}

alias nvm='nvm_init'
alias rvm='rvm_init'
alias pyenv='pyenv_init'
