#!/bin/bash

# curl equivalent for wget
wget() {
	file_name=`echo $1 | awk -F "/" '{print $NF}'`
	curl -L -o $file_name $1
}

# Perform a command on each line of a file
rep() {
	if [[ $# != 2 ]]; then
		echo "Usage: rep <cmd> <file>"
		return
	fi

	if [[ ! -f $2 ]]; then
		echo "$2 should be a valid file" 
		return
	fi

	command -v $1
	if [[ $? -ne 0 ]]; then
		echo "$1 should be a valid executable" 
		return
	fi

	while read i; do
		$1 $i	
	done < $2	
}

open_url() {
	if [[ $# != 1 ]]; then
		echo "Usage: open_url <url>"
		return
	fi

	local url
	url=$1

	case `uname -s` in
		Darwin)
			open $url
			;;
		Linux)
			xdg-open $url
			;;
		*)
			echo "Can't open browser. Goto $url"
			;;
	esac
}
